- hosts: 18.236.155.121
  connection: local

  tasks:
    - name: install LAMP
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - php7.2
        state: present
        update_cache: yes

    - name: start Apache
      become: yes
      become_user: root
      service:
        name: apache2
        state: started
        enabled: yes

    - name: create html directory
      file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      become: yes
      become_user: root
      copy:
        src: index.html
        dest: /var/www/html/index.html
  
    - name: deploy script.js
      become: yes
      become_user: root
      copy:
        src: script.js
        dest: /var/www/html/script.js

    - name: deploy style.css
      become: yes
      become_user: root
      copy:
        src: style.css
        dest: /var/www/html/style.css

